# Generated by Django 4.2.3 on 2023-07-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakes.cake', verbose_name='торт'),
        ),
    ]
