# Generated by Django 4.2.3 on 2023-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_berry_price_alter_decor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
